### ISSUE TITLE
Query: Set sysctl values using hiera

### ISSUE THREAD

**Issue by surajbora1** [hercules-team/augeasproviders_sysctl#45]
I would like to set multiple sysctl values using hiera, I have checked augeasproviders module, but it has dependencies on multiple module. Is there any best way to to set sysctl values using hiera using augeasproviders_sysctl.

**Comment by raphink** [comment]
The dependencies to the augeasproviders module are soft, you don't need to install them all if you don't want to.

**Comment by olevole** [comment]
my hiera use case:

modules/profile/manifests/sysctl.pp:
```
class profile::sysctl (
    $entries = {},
) {
  create_resources('sysctl', $entries)
}
```


in the role yaml:
```
classes:
  - profile::sysctl 

profile::sysctl::entries:
  net.ipv4.tcp_rmem:
    value: 4096 87380 16777216
  net.ipv4.tcp_wmem:
    value: 4096 65536 16777216
  net.core.rmem_max:
    value: 16777216
```
